lib/tasks/enju_leaf_tasks.rake
=> 初期設定スクリプトに貸出モジュールの初期データの読み込みを追加

app/models/manifestation.rb
=> TSV出力の"price"を"manifestation_price"に変更

Gemfile, Gemfile.lock, app/controllers/manifestations_controller.rb, app/views/manifestations/_export_detail.html.erb, app/views/manifestations/_export_list.html.erb, app/views/manifestations/index.xlsx.axlsx, app/views/manifestations/show.xlsx.axlsx, spec/controllers/manifestations_controller_spec.rb
`/manifestations.xlsx`, `/manifestations/1.xlsx`としてアクセスします。現時点ではまだタイトルしか出力していません。
fix #1581
=> Manifestationのxlsxテンプレートファイルを追加

db/fixtures/enju_library/search_engines.yml
https://github.com/next-l/enju_leaf/issues/941#issuecomment-567543508= を1.4系に追加するPRです。
=> NDLサーチを既定の外部検索サービスに追加

app/views/page/configuration.html.erb
=> create_type, realize_type, produce_typeのリンクを設定ページに追加

app/views/manifestations/_render_tag_cloud.html.erb, app/views/manifestations/index.html.erb
=> 検索結果のタグクラウドを一時無効化

app/controllers/manifestations_controller.rb, app/models/carrier_type.rb, app/models/manifestation.rb, app/views/carrier_types/_form.html.erb, app/views/manifestations/_form.html.erb, config/locales/enju_leaf_en.yml, config/locales/enju_leaf_ja.yml, spec/controllers/manifestations_controller_spec.rb, spec/system/manifestations_spec.rb
#598 で要望のあった、添付ファイルを削除するためのUIを追加しています。
=> 添付ファイルの削除機能を追加

app/models/manifestation.rb, app/views/manifestations/show.xlsx.axlsx
#1649 の対応です。ひとまずデータを落とさないことを優先して、全項目を文字列型として出力しています。
=> XLSX出力時に文字列型で出力

app/models/item.rb, app/models/manifestation.rb
=> Manifestation・Itemの削除時にカスタム項目を削除

Gemfile, Gemfile.lock, spec/system/baskets_spec.rb, spec/system/checkins_spec.rb
=> turbolinksを削除

Gemfile, Gemfile.lock
=> rails-i18n gemを追加

.env.template, config/environments/development.rb, config/environments/production.rb
#1675 の修正です。<s>`.env`に以下の記述があることを確認してください。</s>
```
QUEUE=enju_leaf_${RAILS_ENV}
```
=> ActiveJobの設定を追加

.env.template, config/application.rb
Enjuから送信するメールの本文中で使用する、Enjuの既定のURLを指定します。
=> 環境変数ENJU_LEAF_BASE_URLを追加

Gemfile, Gemfile.lock, config/sitemap.rb
Sitemaps XMLを出力する[sitemap_generator gem](https://github.com/kjvarga/sitemap_generator)を追加するPRです。1.3系の仮想マシンには導入されていましたが、1.4系には導入されていませんでした。
=> sitemap_generatorを追加

app/models/resource_import_file.rb, spec/fixtures/files/item_update_file.tsv, spec/fixtures/files/resource_import_file_sample1.tsv, spec/models/resource_import_file_spec.rb
#1666 の修正です。TSVファイルに`manifestation_required_role`と`item_required_role`列を追加しています。
=> ManifestationとItemのrequired_roleのインポートを修正

app/controllers/carrier_types_controller.rb, spec/controllers/carrier_types_controller_spec.rb
=> CarrierTypeの添付ファイルの削除を修正

app/views/manifestations/_form.html.erb
=> カスタムプロパティのフォームに改行を追加

db/seeds.rb
=> 新規インストール時にENJU_LEAF_BASE_URLをLibraryGroupに設定

app/controllers/messages_controller.rb, app/models/message.rb
https://github.com/next-l/enju_leaf/issues/1691 の修正です。実際にはMessageのレコードは作成されていますが、Solrのインデックスが更新されていないため、メッセージが届いていないように見えていました。
=> インポート・エクスポート実行後にMessageのインデックスを更新

config/sunspot.yml, docker-compose.yml, solr/configsets/sunspot/conf/schema.xml, spec/models/manifestation_spec.rb
=> Solrのイメージを8.x系に更新

app/models/picture_file.rb, spec/models/picture_file_spec.rb
=> 画像ファイルの表示順序が変更できないのを修正

app/models/concerns/enju_circulation/enju_manifestation.rb, app/views/manifestations/_manifestation.html.erb, spec/models/manifestation_spec.rb, spec/system/manifestations_spec.rb, spec/views/manifestations/index.html.erb_spec.rb
=> 非ログイン時でも予約リンクを表示するよう変更

app/assets/stylesheets/enju.css
=> ヘッダー・フッターの横幅を指定

app/assets/stylesheets/enju_leaf.css, app/assets/stylesheets/mirador.css, app/views/manifestations/_export_detail.html.erb, app/views/manifestations/_iiif_viewer.html.erb, app/views/manifestations/_show_detail_librarian.html.erb, app/views/manifestations/_show_detail_user.html.erb, config/locales/enju_leaf_en.yml, config/locales/enju_leaf_ja.yml
=> IIIFの埋め込みビューワを追加

.github/workflows/pages.yml, docs/index.md
`docs`ディレクトリの中身をGitHub Pagesで公開するように設定しています。
=> GitHub Pagesのワークフローファイルを追加

Gemfile, Gemfile.lock
データベースの制約の設定をチェックするgem。
https://github.com/djezzzl/database_consistency
=> database_consistency gemを追加

app/controllers/active_storage/blobs/proxy_controller.rb, app/controllers/active_storage/blobs/redirect_controller.rb, spec/requests/iiif_presentations_controller_spec.rb, spec/requests/manifestations_controller_spec.rb, spec/requests/oai_controller_spec.rb, spec/system/manifestations_spec.rb
=> ActiveStorageのファイルダウンロードに認可処理を追加

app/views/user_groups/show.html.erb, spec/system/user_groups_spec.rb
https://github.com/next-l/enju_leaf/issues/1783 の修正です。
=> 利用者グループの編集リンクを修正

app/mailers/notifier.rb, app/models/concerns/enju_circulation/enju_item.rb, app/models/item.rb, app/policies/agent_policy.rb, app/policies/item_policy.rb, app/policies/manifestation_policy.rb, app/views/agents/_index_agent.html.erb, app/views/agents/show.html.erb, app/views/manifestations/_holding.html.erb, app/views/manifestations/_manifestation.html.erb, app/views/manifestations/_manifestation.json.jbuilder, app/views/manifestations/_manifestation_list.html.erb, app/views/manifestations/_reservation.html.erb, app/views/manifestations/_show_detail_librarian.html.erb, app/views/manifestations/_show_detail_user.html.erb, app/views/manifestations/_tab_list.html.erb, app/views/manifestations/_tab_menu.html.erb, app/views/manifestations/index.text.ruby, app/views/manifestations/index.xlsx.axlsx, app/views/manifestations/show.html+phone.erb, app/views/manifestations/show.html.erb, app/views/manifestations/show.js.erb, app/views/manifestations/show.text.ruby, app/views/manifestations/show.xlsx.axlsx, app/views/notifier/manifestation_info.en.text.erb, app/views/notifier/manifestation_info.ja.text.erb, spec/fixtures/item_has_use_restrictions.yml, spec/support/vcr.rb, spec/system/manifestations_spec.rb
参照権限がないレコードが一覧に表示されていたのを修正しています。
=> Item・Manifestation・Agentのスコープが有効になっていなかったのを修正

app/models/concerns/enju_loc.rb, app/models/concerns/enju_ndl.rb, app/models/concerns/enju_nii.rb, app/models/concerns/enju_nii/enju_manifestation.rb, app/models/import_request.rb
https://github.com/next-l/enju_leaf/issues/1799#issuecomment-1602763362 の修正です。以下のようなメッセージを表示するようにしています。
=> インポート時に資料が見つからなかった場合のエラーメッセージを修正

app/models/concerns/enju_oai/oai_model.rb, app/models/doi_record.rb, app/models/manifestation.rb, app/models/resource_import_file.rb, db/migrate/20230818052023_create_doi_records.rb, db/schema.rb, spec/factories/doi_records.rb, spec/models/doi_record_spec.rb, spec/models/resource_import_file_spec.rb
https://github.com/next-l/enju_leaf/issues/1056 で議論したもので、当時のmasterブランチで作業中だったもののうち、まずDOIを扱うモデルのみを追加しています。
=> DoiRecordモデルを追加

app/mailers/agent_import_mailer.rb, app/mailers/event_export_mailer.rb, app/mailers/event_import_mailer.rb, app/mailers/notifier.rb, app/mailers/resource_export_mailer.rb, app/mailers/resource_import_mailer.rb, app/mailers/user_export_mailer.rb, app/mailers/user_import_mailer.rb, app/models/library_group.rb, app/views/library_groups/_form.html.erb, app/views/library_groups/index.html.erb, app/views/library_groups/show.html.erb, app/views/page/opensearch.xml.builder, db/migrate/20191216131755_add_email_to_library_group.rb, db/schema.rb, db/seeds.rb, spec/fixtures/library_groups.yml, spec/models/library_group_spec.rb
https://github.com/next-l/enju_leaf/issues/1496 の実装です。
=> 図書館全体のメールアドレスをlibrary_groupsテーブルに保存

app/models/order.rb, db/migrate/20081009062130_create_orders.rb, db/schema.rb, spec/factories/order_lists.rb, spec/factories/orders.rb, spec/factories/purchase_requests.rb, spec/fixtures/orders.yml, spec/models/order_spec.rb
=> ordersテーブルからstateカラムを削除

.github/workflows/rubyonrails.yml, nginx/templates/production.conf.template-sample
サンプルファイルをコピーして使えるようにしています。
https://github.com/next-l/enju_leaf/wiki/Production
=> nginxのproduction環境の設定ファイルを修正

app/models/agent.rb, app/models/concerns/enju_ndl/enju_manifestation.rb, app/views/agents/show.html.erb, spec/models/ndl_book_spec.rb
https://github.com/next-l/enju_leaf/issues/1325 の実装です。
=> NDLサーチからのインポート時にNDLAのIDを保存

app/views/manifestations/index.xlsx.axlsx
https://github.com/next-l/enju_leaf/issues/1838 の修正です。
=> xlsxによる検索一覧のエクスポートで、先頭の"0"が消えるのを修正

config/locales/enju_biblio_ja.yml
#1841 に対応するもので、original_titleなどの一部の項目を変更しています。
=> Manifestationの一部の項目のラベルをNCR2018にあわせるよう変更

app/helpers/picture_files_helper.rb
https://railsguides.jp/active_storage_overview.html#%E7%94%BB%E5%83%8F%E3%82%92%E5%A4%89%E5%BD%A2%E3%81%99%E3%82%8B
=> 画像表示のリサイズ処理を修正

app/views/ndl_books/index.html.erb, db/fixtures/enju_library/search_engines.yml
https://github.com/next-l/enju_leaf/issues/1858#issuecomment-1950322830 の対応です。
=> NDLサーチのインポート画面の検索リンクを修正

app/models/manifestation.rb, app/models/resource_import_file.rb, spec/fixtures/files/resource_import_file_sample1.tsv, spec/models/resource_import_file_spec.rb
=> pub_dateとdate_of_publicationの両方をエクスポートするよう変更

app/views/manifestations/_show_detail_librarian.html.erb
https://github.com/next-l/enju_leaf/issues/1880 の修正です。
=> 関連資料のタブのテンプレートの読み込みを修正

.github/workflows/rubyonrails.yml, app/controllers/reserves_controller.rb, app/models/concerns/enju_circulation/enju_basket.rb, app/models/reserve.rb, spec/models/basket_spec.rb, spec/models/checked_item_spec.rb, spec/models/reserve_spec.rb
https://github.com/next-l/enju_leaf/issues/1886 の修正です。
=> 予約取置済みの図書の貸出時のエラーを修正

app/views/accepts/_list.html.erb, app/views/accepts/index.js.erb, app/views/accepts/new.html.erb, app/views/checked_items/_list.html.erb, app/views/checkins/_list.html.erb, app/views/withdraws/_list.html.erb, app/views/withdraws/index.js.erb, app/views/withdraws/new.html.erb
`remote`ではなく`local`オプションを使用するようになっているため。
https://railsguides.jp/v6.1/working_with_javascript_in_rails.html#form-with
=> form_withヘルパー内で"local: false"を使用

docker-compose.override.yml.example
=> docker-compose.override.yml.exampleを追加

app/controllers/mission_control_controller.rb, config/application.rb, config/environments/development.rb, nginx/templates/default.conf.template, nginx/templates/production.conf.template-sample
`/jobs`で、Dockerネットワーク内からAdministrator権限を持つユーザのみアクセスできるようにしています。
=> MissionControlControllerを追加

app/controllers/checkouts_controller.rb, app/controllers/concerns/enju_library/controller.rb, app/controllers/events_controller.rb, app/controllers/messages_controller.rb, app/controllers/reserves_controller.rb, app/helpers/checkouts_helper.rb, app/helpers/events_helper.rb, app/helpers/libraries_helper.rb, app/helpers/messages_helper.rb, app/helpers/reserves_helper.rb, app/views/accepts/index.html.erb, app/views/carrier_types/index.html.erb, app/views/carrier_types/show.html.erb, app/views/checkouts/_index_overdue.html.erb, app/views/events/index.html.erb, app/views/reserves/index.html.erb, app/views/withdraws/index.html.erb
ファセット検索などでURLのパラメータをマージする際に使用するヘルパーです。
=> filtered_paramsヘルパーをコントローラーからヘルパーに移動

.env.template, .github/workflows/rubyonrails.yml, Dockerfile, config/database.yml, yarn.lock
コンテナにコンパイル済みのJavaScriptやCSSを含めるようにしています。
=> コンテナのビルド時にrails assets:precompileを実行するよう変更

.env.template, .github/workflows/rubyonrails.yml, Dockerfile, Gemfile, Gemfile.lock, app/assets/config/manifest.js
sprockets gemも4.2にアップデートしています。
=> NODE_OPTIONS=--openssl-legacy-providerを再度追加

app/helpers/enju_biblio/application_helper.rb, app/views/manifestations/_identifier.html.erb, app/views/manifestations/_show_detail_librarian.html.erb, app/views/manifestations/_show_detail_user.html.erb, spec/helpers/enju_biblio/application_helper_spec.rb
=> ndl_bib_id_record_linkヘルパーを追加

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
https://github.com/next-l/enju_leaf/issues/1958 の修正です。
=> 予約のかかっている資料に新規の所蔵を作成できないのを修正

README.md
=> カバレッジのバッジを修正

.github/workflows/rubyonrails.yml, Dockerfile, docker-compose.yml
https://github.com/next-l/enju_leaf/issues/1978 の対応です。
=> Debian 13とPostgreSQL 17のコンテナを使用するように変更
