next-l/enju_leaf

app/models/profile.rb, app/models/role.rb, lib/enju_leaf/master_model.rb, lib/enju_leaf/user.rb, lib/generators/enju_leaf/setup/setup_generator.rb
文字列の末尾という意図と思われる箇所で，`\z`（文字列末尾）でなく `\Z`（文字列末尾または文字列末尾の改行の直前）が使われています。
おそらく `\z` の誤記だろうと思います。
=> replace \Z with \z in regular expressions

app/views/page/system_information.html.erb
「システムの基本的な情報の表示」ページ (`/page/system_information`) に表示されるバージョン番号について、GemがGitからインストールされている場合にはリポジトリのURLとコミットのハッシュを表示する修正です。
=> Show commit hash in system information if gem installed from git

app/assets/stylesheets/enju_leaf/enju.css
書影の取得元に openBD を設定した場合に、`/manifestations/:id` で書影がサイドバー領域から溢れて表示される問題の修正です
=> Fix width of book jacket overflows from sidebar

app/controllers/picture_files_controller.rb, app/views/agent_import_results/index.html.erb, app/views/checkouts/_index.html.erb, app/views/checkouts/_index_item.html.erb, app/views/checkouts/_index_overdue.html.erb, app/views/checkouts/_index_user.html.erb, app/views/event_import_files/_results.html.erb, app/views/events/index.html.erb, app/views/inventory_files/_results.html.erb, app/views/manifestation_checkout_stats/show.html.erb, app/views/manifestation_reserve_stats/show.html.erb, app/views/manifestations/_export_detail.html.erb, app/views/manifestations/_export_list.html.erb, app/views/profiles/_checkout_list.html.erb, app/views/reserves/index.html.erb, app/views/resource_import_files/_results.html.erb, app/views/user_checkout_stats/show.html.erb, app/views/user_import_files/_results.html.erb, app/views/user_reserve_stats/show.html.erb, spec/system/checkouts_spec.rb, spec/system/reserves_spec.rb, spec/system/user_group_has_checkout_types.rb
#1601 の修正です。予約以外のTSV出力もあわせて修正しています。
fix #1601
=> TSV出力のファイルの拡張子を.textから.txtに変更

app/models/identifier.rb
=> Identifier削除時にManifestationのキャッシュを削除

app/views/event_export_mailer/completed.en.text.erb, app/views/event_export_mailer/completed.ja.text.erb, app/views/event_export_mailer/failed.en.text.erb, app/views/event_export_mailer/failed.ja.text.erb, app/views/resource_export_mailer/completed.en.text.erb, app/views/resource_export_mailer/completed.ja.text.erb, app/views/resource_export_mailer/failed.en.text.erb, app/views/resource_export_mailer/failed.ja.text.erb, app/views/user_export_mailer/completed.en.text.erb, app/views/user_export_mailer/completed.ja.text.erb, app/views/user_export_mailer/failed.en.text.erb, app/views/user_export_mailer/failed.ja.text.erb, spec/fixtures/library_groups.yml, spec/mailers/event_export_mailer_spec.rb, spec/mailers/previews/event_export_mailer_preview.rb, spec/mailers/previews/resource_export_mailer_preview.rb, spec/mailers/previews/user_export_mailer_preview.rb, spec/mailers/resource_export_mailer_spec.rb, spec/mailers/user_export_mailer_spec.rb
資料・催し物・ユーザのエクスポート時の通知メッセージでは、図書館名は各言語での名称のみが表示されることを意図していますが、1.3.6では正しく表示されていません。このため、各言語での名称のみを表示するように修正しています。
=> エクスポート時の通知メッセージで図書館名が正しく表示されていない

app/helpers/enju_biblio/application_helper.rb, spec/helpers/enju_biblio/application_helper_spec.rb
#1565 の対応です。既定で`help.png`を表示するようにしています。
https://github.com/next-l/enju_leaf/blob/main/app/assets/images/icons/help.png
=> 資料形態のアイコンが登録されていない場合、既定のアイコンを表示するよう変更

app/models/user_import_file.rb, spec/fixtures/files/user_update_file4.tsv, spec/models/user_import_file_spec.rb
=> ユーザ一括更新TSVでpassword列が空の場合、パスワードをリセットしないように修正

app/controllers/reserves_controller.rb, app/views/reserves/index.html.erb, spec/fixtures/profiles.yml, spec/system/reserves_spec.rb, spec/views/reserves/index.html.erb_spec.rb
#1015 を実装するPRです。ログイン中のユーザの所属する館を、既定の受け取り館に設定します。
=> 既定の予約の受け取り館を設定

app/assets/stylesheets/enju.css, app/views/manifestations/_carrier_type_facet.html.erb, app/views/manifestations/_export_list.html.erb, app/views/manifestations/_language_facet.html.erb, app/views/manifestations/_library_facet.html.erb, app/views/manifestations/_pub_year_facet.html.erb, app/views/manifestations/_reservable_facet.html.erb, app/views/manifestations/_subject_facet.html.erb
ファセット表示の上下の間隔を調整するPRです。 https://github.com/next-l/enju_leaf/issues/1059#issuecomment-166585861 で指摘のあった、以下の問題を修正しています。
> ただ、少なくとも、今のは、くっつきすぎてて変なのと、予約のフィルタとまぎらわしいからなんとかしたい。
修正前後の表示の例を以下に示します。
現状:
修正後:
=> ファセット表示の上下の間隔を調整

app/controllers/agents_controller.rb, app/controllers/concerns/enju_library/controller.rb, app/controllers/items_controller.rb, app/controllers/manifestations_controller.rb
https://github.com/next-l/enju_leaf/pull/1644 で編集履歴の保存機能を削除しましたが、履歴情報の取得のメソッドが残っていたため、削除します。
=> get_versionメソッドを削除

db/fixtures/enju_library/library_group/translations.yml
#1674 の修正です。
フッターの情報はDBに書き込まれているため、この変更は新規インストールのときにしか反映されません。すでにインストール済みの場合、図書館全体の設定から変更することになります。
https://enju.next-l.jp/library_groups/1/edit
=> マニュアルのURLを1.4のものに更新

.env.template, config/database.yml
以前はコメントアウトされていた。`config/database.yml`の記述よりも優先されることに注意。
=> DATABASE_URLを.env.templateで有効化

config/application.rb
config.i18n.available_localesの設定を追加し、英語と既定のロケールのみを有効化します。これは rails-i18n gem の追加 #1671 で、他の言語のロケールファイルが読み込まれるようになったことによるものです。
fix #1690
=> add config.i18n.available_locales

config/environments/production.rb
環境変数`ENJU_LEAF_ACTION_MAILER_DELIVERY_METHOD`を追加しました。Action Mailerの`delivery_method`を指定できるようにしています。既定値は`test`で、実際にメールを送信するには`smtp`に変更します。  
https://railsguides.jp/action_mailer_basics.html#action-mailer%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B
fix #1694
=> Add delivery method

app/views/manifestations/index.html.erb
検索画面のRSSフィードのリンクを、合計ヒット数の直下に移動しました。
fix #1059
=> relocate the RSS feed link under total_count

app/views/checkouts/_index_item.html.erb, spec/system/checkouts_spec.rb
個別資料の個別の画面で、貸出一覧のRSSとTSVのリンクがエラーになっていたのを修正しています。
fix #1700
=> 個別資料の貸出一覧のRSSとTSVのリンクを修正

app/models/manifestation.rb, app/models/resource_import_file.rb, db/fixtures/enju_biblio/identifier_types.yml, spec/fixtures/identifier_types.yml, spec/fixtures/identifiers.yml, spec/models/manifestation_spec.rb
資料TSVのエクスポートの際、一部のIdentifier項目が重複してエクスポートされており、このTSVを使用したインポートの際にエラーを起こしていました。
https://github.com/next-l/enju_leaf/issues/1571#issuecomment-904239297
このPRでは、以下のIdentifierの項目について、後者のみを表示するようにしています。
- identifier:isbn / isbn
- identifier:issn / issn
- identifier:jpno / jpno
- identifier:doi / doi
- identifier:iss_itemno / iss_itemno
- identifier:lccn / lccn
- identifier:ncid / ncid
=> 一部のIdentifierの項目のヘッダー名を修正

app/views/checkouts/edit.html.erb, spec/system/checkouts_spec.rb
=> 貸出延長画面の貸出詳細へのリンクのラベルを「貸出の表示」に変更

config/application.rb, docker-compose.yml, nginx/templates/cantaloupe.conf.template
IIIFサーバのCantaloupeを追加するPRです。
https://cantaloupe-project.github.io/
以下のDockerイメージを利用しています。`docker compose up`で他のコンテナと同時に起動するようになっています。
https://hub.docker.com/r/uclalibrary/cantaloupe
- Cantaloupeへの外部からのアクセスは、リバースプロキシのnginxを経由するようにしている。使用するポートはCantaloupeの既定と同じ 8182/tcp
- Cantaloupeには以下の設定を追加している
```
no_proxy: localhost,web
SOURCE_STATIC: HttpSource
HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_PREFIX: http://web:3000/picture_files/
HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_SUFFIX: '.download'
ENDPOINT_API_ENABLED: 'true'
```
- IIIFのマニフェストファイルは `/iiif/3/{picture_file_id}//info.json` でアクセスする
- IIIFの画像は `/iiif/3/{picture_file_id}/{region}/{size}/{rotation}/{quality}.{format}` でアクセスする
- 例: http://localhost:8182/iiif/3/1/full/max/0/default.jpg
=> IIIFサーバのCantaloupeを追加

config/application.rb, config/environments/development.rb
Rails 6.1で導入されたDNSリバインディング攻撃の対策を、明示的にdevelopment環境でのみ有効化するように変更するPRです。
https://railsguides.jp/configuring.html#actiondispatch-hostauthorization
既定ではdevelopment環境でのみ有効なのですが、 https://github.com/next-l/enju_leaf/pull/1721 でCataloupeからEnju本体にアクセスさせるために設定を変更したところ、development環境以外でもこの設定が有効になってしまい、アプリケーションにアクセスできなくなってしまいました。
=> config.hostsの設定を修正

.env.template, docker-compose.yml
CantaloupeにアクセスするときのURLを指定します。実際にはCantaloupeの`base_uri`に指定する値になり、これがマニフェストファイルでも使用されます。
https://github.com/cantaloupe-project/cantaloupe/blob/develop/cantaloupe.properties.sample#L40
=> 環境変数 CANTALOUPE_BASE_URI を追加

app/views/bookmarks/new.html.erb, spec/system/bookmarks_spec.rb
#1726 の修正です。エラーメッセージの表示に使用する変数名が誤っていました。
=> 新規ブックマーク作成時のエラーメッセージの設定を修正

app/views/manifestations/_book_jacket.html.erb, app/views/manifestations/_colorbox.html.erb, app/views/manifestations/_pickup.html.erb, app/views/manifestations/show.html.erb
資料のサムネイルの表示にはColorboxを使用していますが、これが資料詳細ページでは有効になっているものの、トップページで有効になっていませんでした。
https://www.jacklmoore.com/colorbox/
=> トップページの資料表示でサムネイルのColorboxの表示が無効になっていたのを修正

Dockerfile, lib/enju_leaf/version.rb
1.4.0で `rake assets:precompile` コマンドを実行する際、以下のエラーが発生した。
```
Error: error:0308010C:digital envelope routines::unsupported
```
これはNode.jsのバージョンが新しすぎるためとのこと。
https://zenn.dev/pontagon333/articles/26c89cbc14e81f
EnjuではNode.jsの18.x（LTS版）を指定していたが、このPRで16.xにバージョンを戻している。
=> Nodejsのバージョンを16.xに固定

db/migrate/20221112082227_add_index_to_user_has_roles_on_user_id_and_role_id.rb, db/schema.rb
user_idとrole_idの組み合わせは一意になるため。
=> user_has_rolesテーブルにユニークインデックスを追加

db/migrate/20221112082648_add_index_to_item_has_use_restrictions_on_item_id.rb, db/schema.rb
item_idとuse_restriction_idの組み合わせは一意になるため。
=> item_has_use_restrictionsテーブルにユニークインデックスを追加

db/migrate/20221114063534_add_foreign_key_to_agent_import_files_referencing_user.rb, db/schema.rb
各テーブルに存在するuser_idカラムの値を、usersテーブルのidカラムに存在するものに制限しています。
=> user_idカラムに外部キーを追加

Gemfile, Gemfile.lock
paperclip gemはRuby 3.0の環境でマイグレーションの実行に失敗する不具合がある。
https://stackoverflow.com/questions/66331614/when-i-use-paperclip-migration-error-occur
このため、派生版のkt-paperclipに置き換える。
https://github.com/kreeti/kt-paperclip
なお、ファイル添付機能はActiveStorageに移行しているが、ファイルの移行のため、paperclipの読み込み自体は残している。
=> paperclip gemをkt-paperclip gemに置き換え

.env.template, app/views/user_export_files/index.html.erb, config/storage.yml, docker-compose.yml
MinIOの起動時に、以下を設定します。
- ユーザ名に環境変数`MINIO_ROOT_USER`、パスワードに`MINIO_ROOT_PASSWORD`の中身を設定します。
- 起動時に`enju-leaf-#{Rails.env}`という名前のバケットを作成します。たとえば、development環境であれば`enju-leaf-development`になります。
=> MinIOのパスワードとバケット名の設定を追加

app/models/event_export_file.rb, spec/models/event_export_file_spec.rb
https://github.com/next-l/enju_leaf/issues/1779 の修正です。`event_export.txt`となります。
=> Eventのエクスポートの際のファイル名を指定

babel.config.js, yarn.lock
`@babel/plugin-proposal-private-methods` を `@babel/plugin-transform-private-methods`に置き換えています。
参考: https://devcenter.heroku.com/articles/getting-started-with-rails6#fix-a-babel-regression
=> babelの非互換エラーを修正

Dockerfile
`ruby-3.1.4`のベースイメージがDebian 12(bookworm)になったため、以前と同じDebian 11(bullseye)を使用するように指定しています。
=> Dockerのイメージタグにruby:3.1.4-bullseyeを指定

nginx/templates/default.conf.template
development環境で起動した際、nginxに以下のエラーが出て、Webブラウザでアクセスできない。
```
enju_leaf-nginx-1       | 2023/07/09 02:39:30 [error] 33#33: *1 upstream sent too big header while reading response header from upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.20.0.8:3000/", host: "localhost:8080"
```
このPRでは、レスポンスヘッダのサイズを16KBに増やしている。
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size
=> nginxのレスポンスヘッダのサイズを増加

.env.template
`.env`ではREDIS_URLにデータベース名を指定できるかのように記述していたが、実際にはRedisではデータベース名を指定できない。  
https://stackoverflow.com/questions/35931043/how-can-i-change-the-name-of-databases-in-redis
=> REDIS_URLの指定方法を修正

.env.template, config/environments/production.rb, docker-compose.yml
バックアップ・リストア・アップデートの手順が複雑になることと、MinIOのライセンスがApache 2.0からAGPLに変わっており、再配布の際に問題が発生する可能性があることから、既定での利用を行わないようにしました。
=> ActiveStorageの保存先をローカルに変更

app/models/concerns/enju_loc/enju_manifestation.rb, app/models/concerns/enju_ndl/enju_manifestation.rb
LC・NDLからのインポートの際、`IdentifierType`でisbnが存在しない場合に作成する処理で、クラス名が間違っていました。ただし、通常IdentifierTypeは削除されないので、問題になることはほとんどないと思います。
=> IdentifierTypeのクラス名の誤りを修正

app/helpers/manifestations_helper.rb, app/models/concerns/enju_loc/enju_manifestation.rb, app/models/concerns/enju_ndl/enju_manifestation.rb, app/models/concerns/enju_nii/enju_manifestation.rb, app/models/isbn_record.rb, app/models/isbn_record_and_manifestation.rb, app/models/manifestation.rb, app/models/resource_import_file.rb, app/views/items/index.text.ruby, app/views/manifestations/_form.html.erb, app/views/manifestations/_google_book_thumbnail.html.erb, app/views/manifestations/_hanmotocom_thumbnail.html.erb, app/views/manifestations/_isbn_record_fields.html.erb, app/views/manifestations/_openbd_thumbnail.html.erb, app/views/manifestations/_show.mods.builder, app/views/manifestations/index.rss.builder, app/views/manifestations/show.html+phone.erb, app/views/notifier/manifestation_info.en.text.erb, app/views/notifier/manifestation_info.ja.text.erb, app/views/reserves/index.text.ruby, db/migrate/20160506144040_create_isbn_records.rb, db/migrate/20170116134120_create_isbn_record_and_manifestations.rb, db/schema.rb, spec/fixtures/isbn_record_and_manifestations.yml, spec/fixtures/isbn_records.yml, spec/models/cinii_book_spec.rb, spec/models/loc_search_spec.rb, spec/models/manifestation_spec.rb, spec/models/ndl_book_spec.rb
https://github.com/next-l/enju_leaf/pull/1814 と同様に、ISBNを扱うモデルを追加しています。
=> IsbnRecordモデルを追加

app/helpers/manifestations_helper.rb, app/models/concerns/enju_loc/enju_manifestation.rb, app/models/issn_record.rb, app/models/issn_record_and_manifestation.rb, app/models/manifestation.rb, app/models/resource_import_file.rb, app/views/manifestations/_form.html.erb, app/views/manifestations/_issn_record_fields.html.erb, app/views/manifestations/_show_detail_librarian.html.erb, app/views/manifestations/_show_detail_user.html.erb, db/migrate/20160319144230_create_issn_records.rb, db/migrate/20170116134107_create_issn_record_and_manifestations.rb, db/schema.rb, spec/fixtures/issn_record_and_manifestations.yml, spec/fixtures/issn_records.yml, spec/models/loc_search_spec.rb, spec/models/resource_import_file_spec.rb
https://github.com/next-l/enju_leaf/pull/1814 と同様に、ISSNを扱うモデルを追加しています。
=> IssnRecordモデルを追加

docker-compose.test.yml, spec/support/capybara.rb
環境変数`SELENIUM_DRIVER_URL`の有無で、使用するドライバーを分けるようにしています。
=> ローカル環境でのsystem specのエラーを修正

app/models/jpno_record.rb, app/models/ndla_record.rb, lib/tasks/enju_leaf_tasks.rake
```
bundle exec rake enju_leaf:migrate_identifiers
```
移行対象は以下です。
* isbn -> IsbnRecord
* issn, issn_l -> IssnRecord
* ncid -> NcidRecord
* lccn -> LccnRecord
* iss_itemno -> NdlBibIdRecord
* jpno -> JpnoRecord
* doi -> DoiRecord
=> Identifierモデルの移行タスクを追加

docker-compose.yml
他のコンテナには同オプションが指定されていたのですが、redisだけ抜けていました。
=> redisコンテナに"restart: always"オプションを追加

db/seeds.rb
データベースの初期化コマンド`rails db:prepare`を実行できるようにするため。このコマンドで、データベースの作成と`rails db:seed`コマンドをまとめて実行できる。
https://railsguides.jp/active_record_migrations.html#%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%82%92%E6%BA%96%E5%82%99%E3%81%99%E3%82%8B
インストールの手順も修正すること。
=> rails db:seedコマンドの中でrake enju_leaf:setupタスクを実行

.github/workflows/rubyonrails.yml, Dockerfile, config/application.rb
Rails 7.0では、Active Storageでの画像変換でlibvipsを使用するようになっている。
https://railsguides.jp/v7.0/upgrading_ruby_on_rails.html#active-storage%E3%81%AE%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%AE%E3%83%90%E3%83%AA%E3%82%A2%E3%83%B3%E3%83%88%E3%83%97%E3%83%AD%E3%82%BB%E3%83%83%E3%82%B5%E3%81%8C-vips%E3%81%AB%E5%A4%89%E6%9B%B4
=> libvips42をインストール

app/helpers/enju_biblio/application_helper.rb, spec/factories/identifiers.rb, spec/helpers/enju_biblio/application_helper_spec.rb
https://github.com/next-l/enju_leaf/issues/1855 の対応。
NDLサーチの書誌ID`R100000039-I001413988-00`は、`R100000039-I3377584`に付け替えられているが、ホスト名を`iss.ndl.go.jp`にすれば、新しいIDにリダイレクトされる。つまり、今までにEnjuにインポートされたNDLサーチの書誌IDがリンク切れになることはない。
https://iss.ndl.go.jp/books/R100000039-I001413988-00
しかし、1.4.4では古いIDもリンク先が`ndlsearch.ndl.go.jp`を使用していた。このPRでは、`-00`で終わる書誌IDについては、リンク先に`iss.ndl.go.jp`を使用するようにしている。
=> NDLサーチの書誌IDが'-00'で終わる場合、NDLサーチのリンク先にiss.ndl.go.jpを使用

app/views/libraries/show.html.erb, spec/system/libraries_spec.rb
https://github.com/next-l/enju_leaf/issues/1871 の修正です。
=> 書棚ごとの冊数の表示にcounter_cacheを使用しないよう変更

app/models/agent_import_file.rb, app/models/event_export_file.rb, app/models/event_import_file.rb, app/models/import_request.rb, app/models/manifestation_checkout_stat.rb, app/models/manifestation_reserve_stat.rb, app/models/message.rb, app/models/reserve.rb, app/models/resource_export_file.rb, app/models/resource_import_file.rb, app/models/user_checkout_stat.rb, app/models/user_export_file.rb, app/models/user_import_file.rb, app/models/user_reserve_stat.rb, lib/tasks/enju_biblio_tasks.rake, lib/tasks/enju_circulation_tasks.rake, lib/tasks/enju_event_tasks.rake, lib/tasks/enju_leaf_tasks.rake, lib/tasks/enju_library_tasks.rake, lib/tasks/enju_message_tasks.rake
`statesman:backfill_most_recent`タスクが正常に実行されていなかったのを修正しています。
rakeタスク内で同名のタスクを呼び出すには、`Rake::Task#reenable`を使用する必要がある。
https://qiita.com/yokozawa/items/c7ff1f5131cefd3f6aea
=> most_recentカラムの移行を修正

Gemfile, Gemfile.lock
Ruby 3.2以上のテストが追加されているとのこと。
https://github.com/sunspot/sunspot/releases/tag/v2.7.0
=> sunspot 2.7に更新

app/views/carrier_types/_form.html.erb, app/views/library_groups/_form.html.erb, app/views/picture_files/_form.html.erb, app/views/picture_files/edit.html.erb, app/views/picture_files/new.html.erb
一部のファイルアップロード用のフォームで、選択対象を画像ファイルに限定しています。
=> 画像のフォームに"accept: 'image/*'"を追加

config/routes.rb
Rails組み込みのヘルスチェックエンドポイントを有効化しています。`/up`でステータスコード200か500を返します。
https://railsguides.jp/v7.1/action_controller_overview.html#%E7%B5%84%E3%81%BF%E8%BE%BC%E3%81%BF%E3%81%AE%E3%83%98%E3%83%AB%E3%82%B9%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88
=> ヘルスチェックエンドポイントを有効化

app/models/agent_import_file_transition.rb, app/models/bookmark_stat_transition.rb, app/models/event_export_file_transition.rb, app/models/event_import_file_transition.rb, app/models/import_request_transition.rb, app/models/manifestation_checkout_stat_transition.rb, app/models/manifestation_reserve_stat_transition.rb, app/models/message_transition.rb, app/models/order_list_transition.rb, app/models/reserve_transition.rb, app/models/resource_export_file_transition.rb, app/models/resource_import_file_transition.rb, app/models/user_checkout_stat_transition.rb, app/models/user_export_file_transition.rb, app/models/user_import_file_transition.rb, app/models/user_reserve_stat_transition.rb, db/migrate/20240824034303_convert_statesman_metadata_column_to_jsonb.rb, db/schema.rb, spec/fixtures/order_list_transitions.yml, spec/fixtures/reserve_transitions.yml
1.4系以降ではPostgreSQLのみを使用しているため、JSONB型を利用できる。  
https://github.com/gocardless/statesman?tab=readme-ov-file#using-postgresql-json-column
=> statesman gemで使用しているmetadataカラムをJSONB型に変換

Gemfile.lock, app/helpers/enju_manifestation_viewer/book_jacket_helper.rb, app/models/library_group.rb, db/migrate/20240824070315_convert_library_group_settings_to_json.rb, db/schema.rb, spec/fixtures/library_groups.yml, spec/models/library_group_spec.rb
もともとJSONに変換して保存している。なお、現状のアプリケーションでは未使用といってよい。
=> library_groupsテーブルのsettingsカラムをJSONB型に変換

app/views/agent_import_files/show.html.erb, app/views/event_export_files/show.html.erb, app/views/event_import_files/show.html.erb, app/views/page/configuration.html.erb, app/views/resource_export_files/show.html.erb, app/views/resource_import_files/show.html.erb, app/views/user_export_files/show.html.erb, app/views/user_import_files/show.html.erb, config/locales/enju_leaf_en.yml, config/locales/enju_leaf_ja.yml
Mission Controlの画面へのリンク`/jobs`の文字列を設定しています。
=> 非同期処理用のリンクのラベルを追加

app/controllers/library_groups_controller.rb, app/models/library_group.rb, app/views/page/_menu.html.erb, config/locales/enju_leaf_en.yml, config/locales/enju_leaf_ja.yml
かつて電子リソース管理機能を別途作成しようとして、設定のみ存在していました。作成の見込みがないため、削除します。
=> erms_urlの設定を削除

app/models/concerns/enju_circulation/enju_basket.rb, app/models/concerns/enju_circulation/enju_item.rb, spec/controllers/checked_items_controller_spec.rb
https://github.com/next-l/enju_leaf/issues/1924#issuecomment-2586407275 の修正です。
実際には次のコミットにも修正を含みます。 https://github.com/next-l/enju_leaf/commit/25c9b4cdcfa990c2ed9fb793c05fba39f3981147
=> 複数冊の予約取り置きの割り当てを修正

app/helpers/enju_manifestation_viewer/book_jacket_helper.rb, app/models/library_group.rb, spec/fixtures/library_groups.yml, spec/helpers/book_jacket_helper_spec.rb
Amazonは書影の取得元としてサポートしなくなっているが、ヘルパーが残っていた。
=> Amazonの書影表示ヘルパーを削除

app/views/page/system_information.html.erb
現在の画面では、Rubyと依存するgemのバージョンは表示されるが、Enjuのバージョンが表示されていないので、表示するように修正する。  
https://enju.next-l.jp/page/system_information
=> 「システムの基本的な情報の表示」画面にEnjuのバージョンを表示
